### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by Lockedd** [gpoudel/gitFPL#1]
That is a cool website you have built! 
Could you share the links to the API JSON data you used for your tables?

So far I have found these:
    All player/team data and more: https://fantasy.premierleague.com/drf/bootstrap-static
    Specific player: https://fantasy.premierleague.com/drf/element-summary/[player_id]
    Example Ospina: https://fantasy.premierleague.com/drf/element-summary/1

But I'm wondering where to find things like price watch, injuries?

**Comment by gpoudel** [comment]
Thanks, 
Almost everything at the moment is coming from :  
https://fantasy.premierleague.com/drf/bootstrap-static 
To track daily price changes and injuries/suspensions - i compare the data on daily basis (i.e. compare yesterday's json to today's) and take the difference.

For  player's fixture difficulty rating table I use:
 https://fantasy.premierleague.com/drf/element-summary/[player_id] 
looping through each player. But this scripts need to run only once every game week.

You can also check the status of each team using this json link - https://fantasy.premierleague.com/drf/entry/[team-id]/history
eg: https://fantasy.premierleague.com/drf/entry/12345/history 
Please note: you have to be logged in to FPL website to use this link.

I had plans to make weekly summary/analysis of top 1000 (or so)  based on the above link but so far not done anything about it.

If you have any other questions, let me know.
